VersionRamCustom:27
VersionVanillaName:1.20.1
VersionOriginal:1.20.1
VersionOriginalMain:20
VersionForge:47.4.0
VersionArgumentIndie:1
VersionRamType:1
VersionArgumentJavaSelect:{"Path":"C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.4.8-hotspot\\bin\\","VersionString":"1.17.0.4","IsJre":false,"Is64Bit":true,"IsUserImport":false}
VersionAdvanceJvm:-Drhino.opt.level=9
VersionApiCode:47040000
VersionRamOptimize:1
ReleaseTime:2023-06-12 21:25
VersionLiteLoader:False
IsStar:False
VersionOriginalSub:1
Logo:PCL\Logo.png
Info:正式版 1.20.1, Forge 47.4.0
VersionArgumentIndieV2:True
VersionAdvanceDisableModUpdate:True
LogoCustom:True
State:6
VersionVanilla:20.0.1
