[[ranks]]
  tier = 0
  numAffixes = 0
  defaultColor = 0xffffff
  chance = 1.0
  growthFactor = 0
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 1
  numAffixes = 1
  defaultColor = 0xffff00
  chance = 0.15
  growthFactor = 2
  effects = ["minecraft:regeneration;0", "kubejs:fictional;0"]
  presetAffixes = []
[[ranks]]
  tier = 2
  numAffixes = 2
  defaultColor = 0xff9900
  chance = 0.15
  growthFactor = 4
  effects = ["minecraft:regeneration;1", "minecraft:glowing;0", "minecraft:resistance;0", "kubejs:fictional;1"]
  presetAffixes = []
[[ranks]]
  tier = 3
  numAffixes = 3
  defaultColor = 0x66ffff
  chance = 0.1
  growthFactor = 6
  effects = ["minecraft:regeneration;2", "minecraft:glowing;0", "minecraft:resistance;1", "kubejs:fictional;2"]
  presetAffixes = []
[[ranks]]
  tier = 4
  numAffixes = 3
  defaultColor = 0xcc33ff
  chance = 0.1
  growthFactor = 8
  effects = ["minecraft:regeneration;3", "minecraft:glowing;0", "minecraft:resistance;2", "kubejs:fictional;3"]
  presetAffixes = []
[[ranks]]
  tier = 5
  numAffixes = 3
  defaultColor = 0xcfffff
  chance = 0.0
  growthFactor = 10
  effects = ["minecraft:regeneration;4", "minecraft:glowing;0", "minecraft:resistance;2", "kubejs:fictional;4"]
  presetAffixes = []