
["根源吞噬"]
	#附魔最高等级
	#Range: 1 ~ 10
	max_level = 3
	#伤害转化为目标身上'根源值'的比例 (0.1代表10%)
	#Range: 0.0 ~ 1.0
	accumulation_rate = 0.05
	#每点根源值提供的额外伤害倍率
	#Range: 0.0 ~ 5.0
	bonus_multiplier = 0.1

["魔虚罗"]
	#每次受到相同类型伤害时，抗性提升的倍率 (1.01代表提升1%)
	#Range: 1.0 ~ 2.0
	adapt_increment = 1.01
	#最大减伤比例百分比 (默认90代表最高减免90%伤害)
	#Range: 0.0 ~ 100.0
	max_reduction = 20.0
	#当受到不同类型伤害时，其他已有抗性的衰减比例 (0.95代表保留95%)
	#Range: 0.0 ~ 1.0
	decay_rate = 0.5

["斩首"]
	#附带此附魔时降低的攻击速度 (默认-0.25代表降低25%)
	#Range: -1.0 ~ 0.0
	speed_debuff = -0.1
	#暴击时额外附带目标最大血量的百分比伤害 (0.1代表10%)
	#Range: 0.0 ~ 1.0
	crit_hp_damage_rate = 0.01
	#若生物无头颅掉落，击杀后经验值的加成倍率 (1.2代表额外获得20%)
	#Range: 1.0 ~ 5.0
	exp_bonus_rate = 1.5

["天穹群星之噬"]
	#每支箭矢的基础暴击伤害加成倍率 (1.0代表+100%)
	#Range: 0.0 ~ 10.0
	base_crit_bonus = 1.0
	#力量附魔对该暴击伤害的额外提升系数 (默认每级力量+5%)
	#Range: 0.0 ~ 1.0
	power_enchant_scaling = 0.05
	#三矢齐发命中时，造成的已损血量百分比伤害 (0.05代表5%)
	#Range: 0.0 ~ 1.0
	missing_hp_damage_rate = 0.05
	#在夜晚时，上述百分比伤害的加倍倍率 (默认2倍)
	#Range: 1.0 ~ 5.0
	night_multiplier = 2.0
	#夜晚额外触发的第二段衰减伤害比例 (0.5代表第一段的50%)
	#Range: 0.0 ~ 1.0
	decay_damage_rate = 0.5
	#斩杀判定，当目标血量低于玩家当前血量的多少倍时直接处决 (默认2.0倍)
	#Range: 0.0 ~ 10.0
	execute_threshold_multiplier = 2.0

["灵狩"]
	#灵狩附魔最高等级
	#Range: 1 ~ 10
	max_level = 5
	#击杀非亡灵时每级恢复的最大生命值比例 (0.01代表1%)
	#Range: 0.0 ~ 1.0
	heal_rate_per_level = 0.01
	#击杀亡灵时额外掉落的基础概率 (0.2代表20%)
	#Range: 0.0 ~ 1.0
	drop_base_chance = 0.2
	#击杀亡灵时每级增加的掉落概率 (0.025代表2.5%)
	#Range: 0.0 ~ 1.0
	drop_chance_per_level = 0.025

["穷凶极恶"]
	#降低的攻击力比例 (0.35代表-35%)
	#Range: 0.0 ~ 1.0
	damage_debuff = 0.35
	#增加的暴击伤害倍率 (0.7代表+70%暴击伤害)
	#Range: 0.0 ~ 10.0
	crit_bonus = 0.7

["虚神天掷"]
	#投掷命中时基于玩家攻击力的额外伤害，默认 0.5 (即额外造成50%面板伤害)
	#Range: 0.0 ~ 10.0
	extra_damage_rate = 0.5
	#投掷命中时附带目标当前生命值的百分比伤害，默认 0.05 (即5%)
	#Range: 0.0 ~ 1.0
	hp_damage_rate = 0.05
	#斩杀判定基础值，目标生命值低于(此值 + 最大生命值百分比)时直接处决
	#Range: 0.0 ~ 1000.0
	execute_base_hp = 10.0
	#斩杀判定最大生命值百分比，默认 0.1 代表 10%
	#Range: 0.0 ~ 1.0
	execute_max_hp_rate = 0.1
	#根据敌我血量差距转化的动态加成的最大上限 (3.0代表300%)
	#Range: 1.0 ~ 10.0
	dynamic_bonus_cap = 3.0

["无量之戮"]
	#命中后追加的范围伤害其半径，默认 4.0 格
	#Range: 1.0 ~ 64.0
	aoe_range = 4.0
	#基础魔法伤害，默认 5.0
	#Range: 0.0 ~ 1000.0
	base_aoe_damage = 5.0
	#基于玩家面板攻击力的追加的额外范围伤害比例 (0.3 代表 30%)
	#Range: 0.0 ~ 10.0
	base_aoe_rate = 0.3
	#对高血量目标触发额外释放时的最高生命值百分比魔法伤害 (0.03 代表 3%)
	#Range: 0.0 ~ 1.0
	extra_hp_rate = 0.03
	#命中后造成范围伤害的延迟 (注意喵，单位是ticks，也就是1秒=20ticks，默认 10 代表 0.5 秒)
	#Range: 1 ~ 100
	delay_ticks = 10

["投影成双"]
	#投影的基础伤害，默认 1.0 点
	#Range: 0.0 ~ 1000.0
	base_damage = 1.0
	#每级附魔增加的额外伤害，默认 1.5 点
	#Range: 0.0 ~ 100.0
	damage_per_level = 1.5
	#基于原伤害的额外伤害比例，(0.3 代表 30%)
	#Range: 0.0 ~ 10.0
	damage_rate = 0.3

["撕裂"]
	#单次撕裂伤害中的原伤害比例 (默认 0.1 代表 10%)
	#Range: 0.0 ~ 10.0
	base_rate = 0.1
	#单次撕裂伤害中的已损生命值比例 (默认 0.01 代表 1%)
	#Range: 0.0 ~ 1.0
	missing_hp_rate = 0.01
	#单次撕裂伤害中的最大生命值比例 (默认 0.005 代表 0.5%)
	#Range: 0.0 ~ 1.0
	max_hp_rate = 0.005

["突袭"]
	#攻击无仇恨目标时的伤害倍率 (0.75代表提升75%伤害)
	#Range: 0.0 ~ 10.0
	damage_bonus = 0.75

["消力"]
	#反击伤害为玩家面板攻击力倍率 (3.0代表300%)
	#Range: 0.0 ~ 100.0
	reflect_multiplier = 3.0
	#触发后下一次攻击的伤害提升比例 (0.5代表提升50%)
	#Range: 0.0 ~ 10.0
	next_attack_bonus = 0.5
	#消力触发冷却时间 (单位：秒)
	#Range: 1 ~ 3600
	cooldown_seconds = 5

["剥离"]
	#每次攻击降低目标当前血量的百分比 (0.01代表1%)
	#Range: 0.0 ~ 1.0
	current_hp_strip_rate = 0.01
	#叠满10层后，附加此前总降低血量之和的百分比魔法伤害 (0.2代表20%)
	#Range: 0.0 ~ 10.0
	final_magic_bonus_rate = 0.2

["樱花散"]
	#攻击速度降低的比例 (0.9代表降低90%)
	#Range: 0.0 ~ 1.0
	speed_debuff_rate = 0.9
	#固定增加的攻击力
	#Range: 0.0 ~ 1000.0
	fixed_damage_bonus = 10.0
	#基于面板额外增加的攻击力比例 (1.0代表100%)
	#Range: 0.0 ~ 100.0
	percent_damage_bonus = 1.0
	#斩杀时附加的目标已损血量比例 (0.25代表25%)
	#Range: 0.0 ~ 1.0
	execute_missing_hp_rate = 0.25

["噬魂者"]
	#基础最小掉落数量
	#Range: 0 ~ 64
	min_drop = 1
	#基础最大掉落数量
	#Range: 1 ~ 64
	max_drop = 3
	#亡灵生物掉落倍率
	#Range: 1 ~ 10
	undead_multiplier = 2

["亡灵克星"]
	#每一级对亡灵生物增加的伤害比例 (0.15代表15%)
	#Range: 0.0 ~ 10.0
	bonus_per_level = 0.15

["节肢克星"]
	#每一级对节肢生物增加的伤害比例 (0.15代表15%)
	#Range: 0.0 ~ 10.0
	bonus_per_level = 0.15

["破万法"]
	#每个药水效果提供的固定魔法伤害
	#Range: 0.0 ~ 1000.0
	fixed_damage_per_effect = 5.0
	#药水数量每为2的倍数时，追加的目标最高血量值百分比伤害 (0.02代表2%)
	#Range: 0.0 ~ 1.0
	hp_percent_per_step = 0.02
	#计算额外伤害的药水效果数量上限
	#Range: 1 ~ 100
	max_effect_calculation = 10

