#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jul 01 15:38:03 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
allowUnknownShaders=false
shaderPack=\u3010\u4E2D\u914D\u3011photon_v1.2a.zip
enableShaders=false
