#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 28 00:53:17 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=\u3010\u4E2D\u914D\u3011photon_v1.2a.zip
