onCull = true
MaxEntityEntities = 320
qualityModes = "NORMAL"
RenderWeather = "NORMAL"
FastItemRender = true
RenderDisplayItem = true
blackListedEntities = []
whiteListedEntities = ["modid:goety"]
BlackTagListEntity = []
WhiteTagListEntity = []
isAlwaysShowItemCount = false
startTime = 58.655
onGui = false
GuiRXTX = false
GuiFPS = true
GuiCPU = false
GuiGPU = false
GuiRAM = true
GuiEntityCount = false
GuiPlayerPos = false
GuiServer = true
GuiCameraTarget = false
Mood = false
MaxParticleDistance = 256
WhiteListedParticle = []
BlackListedParticle = []
GuiEasyRamMode = false
GuiDisplayRamUsage = false
GuiX = 4
GuiY = 16
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = true
ParticleMaxAge = 1
GuiViewMode = "EMPTY"
MinDistance = 5
EntityDistance = 128
TickPerformance = true
ParticlePerformance = true
EntityPerformance = false
EntityViewDebug = false
ParticleCountLimit = 17408
BlockBreakParticle = true
AsyncCompute = true
