MaxEntityEntities = 320
qualityModes = "NORMAL"
RenderWeather = "NORMAL"
FastItemRender = true
RenderDisplayItem = true
blackListedEntities = []
whiteListedEntities = ["modid:goety"]
BlackTagListEntity = []
WhiteTagListEntity = []
isAlwaysShowItemCount = false
startTime = 99.73
Hud = false
HudRXTX = false
HudFPS = true
HudCPU = false
HudGPU = false
HudRAM = true
HudPlayerPos = false
HudServer = true
HudCameraTarget = false
Mood = false
MaxParticleDistance = 256
WhiteListedParticle = []
BlackListedParticle = []
GuiEasyRamMode = false
GuiDisplayRamUsage = false
UseAui = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = true
ParticleMaxAge = 1
MinDistance = 5
EntityDistance = 128
ParticlePerformance = true
ParticleCountLimit = 17408
BlockBreakParticle = true
AsyncCompute = true
SoftCull = true
DynamicEntityBudget = true
BlackBlockEntities = []
WhiteBlockEntities = []
MaxBlockEntityCount = 64
BlockEntityDistance = 256
onCull = true
VisibleCulling = true
EntityRenderPerformance = false
CullMode = "COMPATIBILITY"
ParticleFastCollision = false
CullBlockEntity = true
CullEntity = true
CullParticle = true

[[HudTextConfig]]
key = "ruok.options.hud.fps.info"
x = 2
y = 15
enabled = true

[[HudTextConfig]]
key = "ruok.options.hud.system.info"
x = 2
y = 41
enabled = true

[[HudTextConfig]]
key = "ruok.options.hud.playerpos.info"
x = 4
y = 30
enabled = false

[[HudTextConfig]]
key = "ruok.options.hud.server.info"
x = 2
y = 28
enabled = true

[[HudTextConfig]]
key = "ruok.options.hud.cameratarget.info"
x = 4
y = 56
enabled = false

[[HudTextConfig]]
key = "ruok.options.hud.rtxt.info"
x = 4
y = 69
enabled = false
